env:
  - DB=postgresql
branches:
  only:
    - 'master'
    - 'production'
    - /^[0-9]+\.[0-9]+$/
rvm:
  - 2.0.0-p195
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick libmagickwand-dev -qq -y
  - "gem list -d"
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "NOEXEC_DEBUG=1 bundle exec rake db:create RAILS_ENV=test"
  - "NOEXEC_DEBUG=1 bundle exec rake db:schema:load RAILS_ENV=test"
  - "NOEXEC_DEBUG=1 bundle exec rake db:seed RAILS_ENV=test"
  - "sh -e /etc/init.d/xvfb start"
script: "NOEXEC_DEBUG=1 bundle exec rake travis"
